project 'JewelProducts.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JewelProducts' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for JewelProducts
pod 'SwiftyJSON', '~> 4.0'
end
